# Generated by Django 6.0.1 on 2026-02-01 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_Serializer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('country', models.CharField(max_length=10)),
                ('jersy_number', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
