# Generated by Django 6.0.1 on 2026-02-02 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_player_serializer_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('city', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Player_Serializer',
        ),
    ]
